# src/Acme/MailerBundle/Resources/config/services.yml
parameters:
    ip_storage.driver_chain.class: bodakyuriy\IPStorageBundle\DriverChain


services:
    _defaults:
        autowire: true
        autoconfigure: trues
        public: false

    bodakyuriy\IPStorageBundle\Controller\:
        resource: '../../Controller'
        tags:
            - { name: controller.service_arguments }

    bodakyuriy\IPStorageBundle\Service\:
        resource: '../../Service/*'
        public: true

    bodakyuriy\IPStorageBundle\DriverChain: ~

    bodakyuriy\IPStorageBundle\ValidatorChain: ~

    bodakyuriy\IPStorageBundle\Driver\DoctrineDriver\Driver:
        public: true
        tags:
            -  { name: 'ip_storage.driver', alias: 'doctrine' }

    bodakyuriy\IPStorageBundle\Validator\Validator:
        public: true
        tags:
            -  { name: 'ip_storage.validator', alias: 'default' }

    bodakyuriy\IPStorageBundle\Entity\IPStorage: ~